version: '3'
networks:
   movie-network:
       external: true
       name: 'mongo-network'

volumes:
  moviedata:

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://admin:pass@database:27017
      - REDIS_URI=redis://cache
      - ENABLE_WRITING_HANDLERS=false
    networks:
       - movie-network
    depends_on:
      - database
  
  database:
    container_name: mongoDB
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
       - movie-network
    volumes:
       - moviedata:/data/db   

  cache:
    container_name: redis
    image: redis:alpine

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always 
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@database:27017/
    networks:
       - movie-network
    depends_on:
      - database